stages:
  - audit
  - test
  - deploy

image: node:12.14.0-alpine
before_script:
  - npm ci

test:
  stage: test
  needs: [ ]
  script:
    - npm run ci-test
  rules:
    - changes:
        - src/**/*.ts
        - test/**/*.ts
  artifacts:
    paths:
      - coverage/**/*
    expire_in: 1 week
lint:
  stage: audit
  needs: [ ]
  script:
    - npm run lint
  rules:
    - changes:
        - src/**/*
        - .eslintrc.yml
pages:
  stage: deploy
  before_script: [ ]
  needs:
    - test
  script:
    - mv coverage/lcov-report public
  artifacts:
    paths:
      - public
  rules:
    - changes:
        - src/**/*.ts
        - test/**/*.ts

